CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    kis_app_key VARCHAR(255),
    kis_app_secret VARCHAR(255),
    account_number VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE trade_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    ticker VARCHAR(50) NOT NULL,
    action VARCHAR(20) NOT NULL,
    price NUMERIC(38, 2) NOT NULL,
    profit_rate NUMERIC(38, 2),
    timestamp TIMESTAMP NOT NULL
);

CREATE TABLE strategies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    type VARCHAR(50) NOT NULL,
    buy_condition VARCHAR(255),
    sell_condition VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);
